### ISSUE TITLE
Facebook stories 

### ISSUE THREAD

**Issue by adityavarma1234** [ankityadav0294/disable-facebook-news-feed#4]
Facebook stories are still visible after installing this addon on firefox. @ankityadav0294  can you please look into this. For now installing this https://west.io/news-feed-eradicator/

**Comment by ankityadav0294** [comment]
The addon doesn't remove facebook stories. The idea behind the addon is to not fall into the infinte scroll trap of the news feed, i personally haven't seen the need for removing stories as they don't pose any such problem where you continue spending hours and hours on end. Do let me know if you think otherwise.

The feature is good to have but i am not sure if everyone who wants to use this addon to remove news feed also don't want to see stories.

**Comment by shbach** [comment]
I actually came to submit this as well. Stories can still be distracting and a time waster. It's similar in spirit to the news feed so I think it should also be disabled. For those that would still like to see it perhaps it is possible to add a setting to the extension so that they can turn it back on?
