### ISSUE TITLE
No longer working on Android Firefox

### ISSUE THREAD

**Issue by danoliver1** [ankityadav0294/disable-facebook-news-feed#6]
Thanks for this plugin.
Since Firefox for Android had a slight redesign it is no longer working.
Is it possible to bump the version numbers to get it working?

**Comment by ankityadav0294** [comment]
The newer version of browser on Android doesn't let you install all addons.
There is a limited set of addons that you can install right now in android.
https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android
Thanks,
Ankit

**Comment by danoliver1** [comment]
Ok, that's annoying! I'll close this issue as it's outside of your control. Thanks

**Comment by shbach** [comment]
Can this be reconsidered? It's possible to install this extension on Firefox Nightly for Android using a custom collection (see https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)

**Comment by ankityadav0294** [comment]
You can go ahead and create a collection for this. You can add the list of add-ons that you want to try out in the build. This allows you as a user the control as to which collection should be added and what add-ons should be present in this collection.

I can create a collection with just this add-on but Firefox only allows loading one collection at a time, so it would be good for users to create this instead of developers.

I have created a [collection](https://addons.mozilla.org/en-US/firefox/collections/13007300/Disable-Facebook-News-Feed/) with just this add-on.
Collection ID: 13007300
Collection name: Disable-Facebook-News-Feed

if this is the only add-on you want to use, then this collection should suffice. Otherwise, you would need to create a new collection.

**Comment by shbach** [comment]
@ankityadav0294 Even though I am able to add this extension to firefox mobile using collections, the extension itself doesn't work as the newsfeed still displays.
